- smart
- cool
- clean
- dirty
- clever
- honest
- trustworthy
- sexy
- hot
- strong
- shy
- vain
- cocky
- proud
- sneaky
- funny
- clueless
- ditzy
- nice
- generous
- nerdy
- brutal
- sharp
- conniving
- sweet
- popular
- mysterious
- meticulous
- angry
- tidy
- stressed
- chill